openapi: 3.1.0
info:
  title: Tournament
  description: |-
    This API is used as a sandbox to discuss the repository pattern.
  version: 0.0.1
externalDocs:
  description: Source code
  url: https://github.com/sylvaindecout/repository-pattern-example
tags:
  - name: tournament
    description: Back-office operations about tournaments
  - name: users
    description: Back-office operations about users
  - name: selection
    description: Operations related to tournament selection
  - name: roster
    description: Operations about managing player rosters
  - name: player
    description: Operations about a specific player
paths:
  /users/{userId}:
    get:
      tags:
        - users
      summary: Find user
      description: Find a user
      operationId: findUser
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            $ref: '#/components/schemas/UserId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid parameters supplied
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - users
      summary: Upsert user
      description: Create or update a user
      operationId: upsertUser
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            $ref: '#/components/schemas/UserId'
      requestBody:
        $ref: '#/components/requestBodies/UserUpdateRequest'
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid parameters supplied
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tournaments/{tournamentId}:
    get:
      tags:
        - tournament
      summary: Find tournament
      description: Find a tournament
      operationId: findTournament
      parameters:
        - name: tournamentId
          in: path
          description: ID of tournament
          required: true
          schema:
            $ref: '#/components/schemas/TournamentId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tournament'
        '400':
          description: Invalid ID supplied
        '404':
          description: Tournament not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - tournament
      summary: Upsert tournament
      description: Create or update a tournament
      operationId: upsertTournament
      parameters:
        - name: tournamentId
          in: path
          description: ID of tournament
          required: true
          schema:
            $ref: '#/components/schemas/TournamentId'
      requestBody:
        $ref: '#/components/requestBodies/TournamentUpdateRequest'
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Tournament:
      required:
        - id
        - name
        - maxPlayerRosterSize
      properties:
        id:
          $ref: '#/components/schemas/TournamentId'
          readonly: true
        name:
          $ref: '#/components/schemas/TournamentName'
        maxPlayerRosterSize:
          $ref: '#/components/schemas/PlayerRosterSize'
        minimumAge:
          $ref: '#/components/schemas/Age'
    User:
      required:
        - id
        - preferredNickname
        - dateOfBirth
        - city
      properties:
        id:
          $ref: '#/components/schemas/UserId'
          readonly: true
        preferredNickname:
          $ref: '#/components/schemas/Nickname'
        dateOfBirth:
          $ref: '#/components/schemas/LocalDate'
        city:
          $ref: '#/components/schemas/City'
    UserId:
      type: string
      format: uuid
    TournamentId:
      type: string
      format: uuid
    TournamentName:
      type: string
      examples: [ 'Tournament #1' ]
    PlayerRosterSize:
      type: integer
      examples: [ 50 ]
    Nickname:
      type: string
      pattern: '[A-Z]{1,50}'
      examples: [ 'giorno', 'jotaro', 'jolyne', 'joseph' ]
    LocalDate:
      type: string
      format: date
    Age:
      type: integer
      minimum: 16
      examples: [ 20, 35, 25, 21 ]
    City:
      type: string
      minLength: 2
      examples: [ 'naples', 'tokyo', 'orlando', 'new york city' ]
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  requestBodies:
    TournamentUpdateRequest:
      description: Tournament that needs to be created or updated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tournament'
    UserUpdateRequest:
      description: User that needs to be created or updated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
